server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instant_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

# ??mybatis
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    # ??mybatis????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??mybatis???????????  a_column = aColumn
    map-underscore-to-camel-case: true

login-reg:
  jwt:
    employee-secret-key: cyh_handsome
    employee-ttl: 864000000
    employee-token-name: Authorization
    user-secret-key: user_handsome
    user-ttl: 864000000
    user-token-name: Authorization

hanye:
  wechat:
    appid: ${hanye.wechat.appid}
    secret: ${hanye.wechat.secret}

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: cyh_handsome
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: user_handsome
    user-ttl: 86400000
    user-token-name: authentication

  shop:
    address: 广东省广州市番禺区亚运城广场
  baidu:
    ak: ePMydufnJzBBTQlrzKwxAmlpRApLxmOW